### ISSUE TITLE
client: label dimensions inconsistent with previously collected metrics in the same metric family

### ISSUE THREAD

**Issue by mjtrangoni** [HewlettPackard/lustre_exporter#100]
I updated to `v0.01.0-95-g296cb5b`, and I am having this errors with the client metrics. This should be related to #98.
```
An error has occurred during metrics gathering:

6 error(s) occurred:
* collected metric lustre_blocksize_bytes label:<name:"client" value:"lustre-ffff882034315000" > gauge:<value:4096 >  has label dimensions inconsistent with previously collected metrics in the same metric family
* collected metric lustre_inodes_free label:<name:"client" value:"lustre-ffff882034315000" > gauge:<value:6.09518363e+08 >  has label dimensions inconsistent with previously collected metrics in the same metric family
* collected metric lustre_inodes_maximum label:<name:"client" value:"lustre-ffff882034315000" > gauge:<value:6.09555957e+08 >  has label dimensions inconsistent with previously collected metrics in the same metric family
* collected metric lustre_available_kilobytes label:<name:"client" value:"lustre-ffff882034315000" > gauge:<value:6.17488943176e+11 >  has label dimensions inconsistent with previously collected metrics in the same metric family
* collected metric lustre_free_kilobytes label:<name:"client" value:"lustre-ffff882034315000" > gauge:<value:6.18113508516e+11 >  has label dimensions inconsistent with previously collected metrics in the same metric family
* collected metric lustre_capacity_kilobytes label:<name:"client" value:"lustre-ffff882034315000" > gauge:<value:6.191165228e+11 >  has label dimensions inconsistent with previously collected metrics in the same metric family
```

**Comment by mjtrangoni** [comment]
I can confirm that reverting 1b0031349025b3e506cbb60f5eb20d1d688a4a0d it is working again.

**Comment by roclark** [comment]
Thanks @mjtrangoni for passing this along! I will look into this.

For starters, if you don't mind, can you tell me a little about your setup? I see this is a client, but do you also have any storage devices on the same node (MGS, MDS, OSS)?

Also, when you reverted to `1b00313`, are you using that exact commit (ie. the wildcard is added), or one _before_ that commit (no wildcard)? If the latter, are you getting any client metrics?

Thanks again!

**Comment by joehandzik** [comment]
@roclark Based on his initial bug report, it seems that he is using the code just prior to merging #98

**Comment by mjtrangoni** [comment]
@roclark, I just removed the wildcard /* from latest master state. I think this has to do with my vendor update after your commit. By the way it is a sanity check added by Prometheus client.
The server is an MDS server that mount a Lustre Client for testing purposes.
I can give you more information tomorrow.

**Comment by roclark** [comment]
Thanks for the clarification.

> The server is an MDS server that mount a Lustre Client for testing purposes.

I think this might be the key. I haven't verified yet, but I believe there is an inconsistency between the label names for the MDS and client metrics. The 6 metrics you listed above appear in both the client and MDS metric lists. The first label name for each (`"client"` for clients and `"mds"` for MDS's) is different and is throwing the error. @joehandzik we should rethink that first label for instances like these.

Thanks again, that was all the information I needed for the moment.

**Comment by joehandzik** [comment]
@roclark Good to know. I had thrown around the idea of changing that particular label into more of a 'name' label that would be common everywhere, and creating a 'type' label for client/mds/oss/mdt/...

**Comment by roclark** [comment]
Good idea. I think that would probably be the most straightforward and uniform change.

**Comment by joehandzik** [comment]
@roclark The tough part here is that it'll break some dashboarding work out there, so we'll likely want to tag a version prior to this change to enable others to stick with the old labels if they prefer.

**Comment by roclark** [comment]
Good call.

**Comment by mjtrangoni** [comment]
Just for the records. I confirm this solves my problems with the MDS + Client server. Thanks!

**Comment by joehandzik** [comment]
@mjtrangoni Thanks for checking! Also, just a heads up, we're looking to actually lock this in as a full-fledged 1.0 release in the next month or two. So if you have any other suggestions or desires for labeling, we'd love to hear about them in the next few weeks. Really appreciate all the help you've given!
