### ISSUE TITLE
Introduce "Core" and "Extended" as flag concepts

### ISSUE THREAD

**Issue by joehandzik** [HewlettPackard/lustre_exporter#116]
As we've started to create more complex dashboards from these metrics, we're learning that there are just some metrics that we're collecting today that we'll never, ever put in a dashboard. To that end, I think it makes sense to modify our flag methodology to introduce a third flag state. Each metric that we can collect will be tagged with a level of importance:

Core - Viewed as essential for performance monitoring and issue triage.
Extended - Not essential, unlikely to ever be added to a dashboard.

The default run state will likely be "Extended", which would expose everything. But for our purposes, in real customer environments we're likely to use "Core" to save storage space and minimize clutter.

Comments and thoughts welcomed!

**Comment by roclark** [comment]
Closing after the merge of #117.
