### ISSUE TITLE
Feature request: -collector Options

### ISSUE THREAD

**Issue by mjtrangoni** [HewlettPackard/lustre_exporter#119]
Hi,
I want to make a feature request. What about listing the flag options, like `Valid levels: [core, extended, disabled]`? I think it would be more understandable.

```
Usage of ./lustre_exporter:
  -collector.client string
        Enable Client metrics (default "extended")
[...]
  -log.level value
        Only log messages with the given severity or above. Valid levels: [debug, info, warn, error, fatal]
```

Thanks!

**Comment by joehandzik** [comment]
@mjtrangoni We'll figure out a way to do this. Thanks for the suggestion!

**Comment by joehandzik** [comment]
@mjtrangoni Please take a look at PR #121 and let me know if it satisfies this request!
