### ISSUE TITLE
can not get like lustre_capacity_kilobytes in mds node

### ISSUE THREAD

**Issue by wutaizeng** [HewlettPackard/lustre_exporter#125]
Can not found `mds/MDS/osd` in lustre 2.8.0/2.9.0/2.10.0

```
[root@node01 MDS]# pwd
/proc/fs/lustre/mds/MDS
[root@node01 MDS]# ls
mdt  mdt_fld  mdt_out  mdt_readpage  mdt_seqm  mdt_seqs  mdt_setattr  uuid
```

Can found in "osd-ldiskfs/*"

```
[root@node01 ShareEM2-MDT0000]# pwd
/proc/fs/lustre/osd-ldiskfs/ShareEM2-MDT0000
[root@node01 ShareEM2-MDT0000]# ls
auto_scrub  brw_stats  filestotal  fstype            full_scrub_threshold_rate  kbytesfree   mntdev    pdo          read_cache_enable       stats
blocksize   filesfree  force_sync  full_scrub_ratio  kbytesavail                kbytestotal  oi_scrub  quota_slave  readcache_max_filesize  writethrough_cache_enable
```

**Comment by joehandzik** [comment]
Hey @wutaizeng, thank you for the report. This is perfect timing for us, as we're about to start working to eliminate problems like this in the versions that you pointed out (we've been using IEEL 3.x until recently). I expect to have a fix in the next day or two (at worst).

**Comment by joehandzik** [comment]
@wutaizeng, I have looked into this issue with @roclark on his new install of Lustre 2.10.1, and we're encountering this issue along with a few other issues. Our go-forward plan is to cut a v1.0.0 release of our current exporter (DONE) and proceed with a 2.0.0 release that will support lustre 2.10.1 going forward. Our goal is to have this completed sometime in early December.

**Comment by joehandzik** [comment]
@wutaizeng Looks like I held up my date bargain! Please take a look at PR #130 and let us know if this fixes the problems you saw. We are testing with ZFS, but the code was written in such a way that ldiskfs should work too.

**Comment by wutaizeng** [comment]
It fix the problem
