### ISSUE TITLE
Replace govendor with dep

### ISSUE THREAD

**Issue by mjtrangoni** [HewlettPackard/lustre_exporter#127]
Hi @joehandzik,

You could move the vendoring management before `v1.0.0` from `govendor` to [dep](https://github.com/golang/dep), and a vendoring update would be great too.

Thanks!

**Comment by joehandzik** [comment]
Hmm, I think we'll need to save this for v2.0.0 or sneak it into a v1.1.0 or something like that. Apologies for tagging so quickly, but we're trying to move fast to track to a product release. We're happy to work with you to find a path that works for everyone!

**Comment by mjtrangoni** [comment]
Hi @joehandzik ,
I just realized that the log options are not present anymore.
