### ISSUE TITLE
Update readme?

### ISSUE THREAD

**Issue by sknolin** [HewlettPackard/lustre_exporter#140]
"See the issues tab for all known issues. This project is actively maintained by HPE, so you should see a reasonably quick response if you identify a gap."

Is this actively maintained by HPE any more really?

**Comment by joehandzik** [comment]
@sknolin Not as actively as it should be, clearly. I'll wrap back on this and chew through as time allows. All sorts of other work has gotten in the way (not that it's a good enough excuse).

**Comment by joehandzik** [comment]
@sknolin Objectionable text removed, and a better faith effort will be made to work through the outstanding requests here. Sincere apologies.
