### ISSUE TITLE
Ensure that all existing code handles cases of missing data with graceful partial failure 

### ISSUE THREAD

**Issue by joehandzik** [HewlettPackard/lustre_exporter#17]
Essentially, avoid the same situation we ran into with weirdly missing data from the stats file.

**Comment by joehandzik** [comment]
@roclark I took a look at this yesterday and didn't see anything, expect for *maybe* in the brw_stats parser. Can you double check that and, if you think there's no problem, close out this issue? Specific line to start at (I think): https://github.com/HewlettPackard/lustre_exporter/blob/master/sources/procfs.go#L455

**Comment by roclark** [comment]
We are good on BRW stats due to how the metrics are written (we get all or nothing). Since the `metricMap` is allocated at the top of the function where we actually parse data, there isn't a concern about accessing invalid memory.
