### ISSUE TITLE
/proc/fs/lustre/health_check

### ISSUE THREAD

**Issue by knweiss** [HewlettPackard/lustre_exporter#46]
Please add the new metric `lustre_health` for `/proc/fs/lustre/health_check`.
```
$ cat /proc/fs/lustre/health_check
healthy
```
(or `not healthy`)

**Comment by joehandzik** [comment]
We'll get it up there as soon as we can!

**Comment by joehandzik** [comment]
@roclark to the rescue, closing this issue (let us know if you have any concerns @knweiss)
