### ISSUE TITLE
Convert counters to gauges where applicable

### ISSUE THREAD

**Issue by roclark** [HewlettPackard/lustre_exporter#47]
As identified in #44, we will need to convert some metric types from `counter` to `gauge` as some go up and down. Some examples are filesystem capacities, number of operations in flight, setting/tuning values, etc.

**Comment by knweiss** [comment]
One [hint](https://prometheus.io/docs/instrumenting/writing_exporters/#types) regarding this issue: Another option is to use an `UNTYPED` metric.

> Often it won’t be obvious what the type of a metric is (especially if you’re automatically processing a set of metrics), use `UNTYPED` in that case. In general `UNTYPED` is a safe default.

**Comment by joehandzik** [comment]
This is complete once we merge #44.

**Comment by roclark** [comment]
Closing after merge of #44.
