### ISSUE TITLE
Semantic Versioning and CHANGELOG.md

### ISSUE THREAD

**Issue by mjtrangoni** [HewlettPackard/lustre_exporter#55]
I wanted to point you out to use [semantic versioning](http://semver.org/) for versioning.

See that you have `1.00.0-rc.1` instead of `1.0.0-rc.1` in [VERSION](https://github.com/HewlettPackard/lustre_exporter/blob/master/VERSION) and `v0.01.0` instead of `v0.1.0` released.

A `CHANGELOG.md` file would be a nice to have too.

Thanks!

**Comment by joehandzik** [comment]
Yeah, I see that I made a mistake in adding an extra zero in the middle there. I can drop the extra zero in future releases and versions. Thanks for pointing that out!

We'll add a changelog too, certainly.

**Comment by joehandzik** [comment]
Fixed semantic versioning via #63, will close once the CHANGELOG file is added.
