### ISSUE TITLE
Converge md_stats and some job_stats statistics into a single metric

### ISSUE THREAD

**Issue by joehandzik** [HewlettPackard/lustre_exporter#64]
We should likely converge all md_stats values and some job_stats values into a single metric per file instance, with labels to distinguish the separate statistic values.

**Comment by knweiss** [comment]
https://prometheus.io/docs/practices/instrumentation/#use-labels

> Use labels : For example, rather than http_responses_500_total and http_responses_403_total, create a single metric called http_responses_total with a code label for the HTTP response code. You can then process the entire metric as one in rules and graphs.
