### ISSUE TITLE
Add client statistics

### ISSUE THREAD

**Issue by joehandzik** [HewlettPackard/lustre_exporter#69]
Use this issue to track our initial effort to add Lustre client statistics to the exporter.

**Comment by roclark** [comment]
Todo:

- [ ] Add `singlestat` metrics from clients
- [ ] Expand `*stats` files to include missing metrics

**Comment by joehandzik** [comment]
I added a 'phase 3' here, FYI (rpcstats). No rush on it, just a reminder that we had a different potential user ask about it.
