### ISSUE TITLE
Cases exist where type label is unpopulated for some client stats

### ISSUE THREAD

**Issue by joehandzik** [HewlettPackard/lustre_exporter#94]
Example from the user: 

lustre_pages_per_rpc{="",client="lustref-OST0000-osc-xxx",operation="read",size="1"} 4
lustre_rpcs_offset{="",client="lustref-OST0000-osc-xxx",operation="read",size="0"} 7

Working output:

lustre_rpcs_in_flight{client="lustref-MDT0000-mdc-ffff882f5369e000",operation="read",size="0",type="mdc"} 0
lustre_rpcs_in_flight{client="lustref-OST0000-osc-xxx",operation="read",size="0",type="osc"} 0

**Comment by roclark** [comment]
Closed with #95
