### ISSUE TITLE
RPC and console metrics names 

### ISSUE THREAD

**Issue by mjtrangoni** [HewlettPackard/lustre_exporter#96]
Hi,
I was testing the latest metrics, checking them against `promtool check-metrics` too, and found some new issues.
```
lustre_pages_per_rpc: counter metrics should have "_total" suffix
lustre_rpcs_offset: counter metrics should have "_total" suffix
lustre_console_max_delay_centiseconds: use base unit "seconds" instead of "centiseconds"
lustre_console_min_delay_centiseconds: use base unit "seconds" instead of "centiseconds"

Note that I have ignored the {kilo,mega}bytes warnings.

**Comment by joehandzik** [comment]
Thanks for the heads up, though similar to the kilobyte and megabyte warnings, I expect that we'll leave the centiseconds base unit for now (converting just adds an extra layer of processing). For the first two, we'll either change them to gauges or add the _total.

**Comment by joehandzik** [comment]
@roclark I think lustre_rpcs_offset should clearly be a gauge, but I'm not as clear on what lustre_pages_per_rpc should be. The help text makes me think it really should be a counter, but can that value go down at all?
